owner: fractava
repo: status

sites:
  - name: Website
    url: https://fractava.com
  - name: Website Backend
    url: https://backend.fractava.com
  - name: Nextcloud
    url: https://nextcloud.fractava.com
  - name: Onlyoffice
    url: https://onlyoffice.cloud.fractava.com/
  - name: Overleaf
    url: https://overleaf.treffler.cloud/
  - name: Aptitron (Server)
    url: http://aptitron.fractava.com/
  - name: Greenytron (Server)
    url: http://cloud.fractava.com/

status-website:
  cname: status.fractava.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/fractava/resources/master/Logos/Symbol/gro%C3%9F/transparenter%20Hintergrund/Farbe%20schwarz.png
  name: FRACTAVA Status
  introTitle: "FRACTAVA Services Status"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://fractava.com
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
