owner: fractava
repo: status

sites:
  - name: Aptitron (Server)
    url: http://aptitron.fractava.com/
    icon: https://www.proxmox.com/images/proxmox/Proxmox-logo-stacked-840px.png
  - name: Website Backend
    url: https://backend.fractava.com
    icon: https://raw.githubusercontent.com/fractava/resources/master/Logos/Symbol/gro%C3%9F/transparenter%20Hintergrund/Farbe%20weiß.png
  - name: Greenytron (Server)
    url: http://cloud.fractava.com/
    icon: https://craftassets.unraid.net/uploads/logos/unraid-stacked-dark.svg
    expectedStatusCodes:
      - 401
  - name: Reverse Proxy
    url: https://proxy.treffler.cloud
    icon: https://nginxproxymanager.com/icon.png
  - name: Nextcloud
    url: https://nextcloud.fractava.com
    icon: https://nextcloud.com/wp-content/themes/next/assets/img/logo/logo_nextcloud_white.svg?x53054
  - name: Onlyoffice
    url: https://onlyoffice.cloud.fractava.com/
    icon: https://static-www.onlyoffice.com/images/press-downloads/logos/logo_symbol_color.svg
  - name: Overleaf
    url: https://overleaf.treffler.cloud/
    icon: https://images.ctfassets.net/nrgyaltdicpt/h9dpHuVys19B1sOAWvbP6/5f8d4c6d051f63e4ba450befd56f9189/ologo_square_colour_light_bg.svg
  - name: Website
    url: https://fractava.com
    icon: https://raw.githubusercontent.com/fractava/resources/master/Logos/Symbol/gro%C3%9F/transparenter%20Hintergrund/Farbe%20weiß.png
  - name: BirdsiteLive
    url: https://birdsitelive.treffler.cloud/
    icon: https://raw.githubusercontent.com/fractava/status/master/img/BirdsiteLive.png
  - name: Invidious
    url: https://invidious.treffler.cloud/
    icon: https://raw.githubusercontent.com/iv-org/invidious/master/assets/mstile-150x150.png
  - name: CubeS (Server)
    url: http://status.macbrayne.de/
    icon: https://craftassets.unraid.net/uploads/logos/unraid-stacked-dark.svg

status-website:
  cname: status.fractava.com
  theme: night
  css: "#sapper > main > section.live-status > article:nth-child(n+2):nth-child(-n+2), #sapper > main > section.live-status > article:nth-child(n+4):nth-child(-n+10) { margin-left: 40px; }"
  logoUrl: https://raw.githubusercontent.com/fractava/resources/master/Logos/Symbol/gro%C3%9F/transparenter%20Hintergrund/Farbe%20weiß.png
  name: FRACTAVA Status
  introTitle: "FRACTAVA Services Status"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://fractava.com
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
